<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Địa chỉ',
    'All' => 'Tất cả',
    'Birtday' => 'Ngày sinh',
    'Customer type' => 'Loại KH',
    'Debit' => 'Ghi nợ',
    'Email' => 'Email',
    'Gender' => 'Giới tính',
    'Last order' => 'Lần mua cuối',
    'Phone number' => 'Số điện thoại',
    'Remarks' => 'Ghi chú',
    'Retail' => 'Khách lẽ',
    'Wholesale' => 'Khách sỉ',
    'Customer code' => 'Mã khách hàng',
    'Customer code OR Customer name OR Customer phone number' => 'Nhập mã hoặc tên hoặc số điện thoại để tìm kiếm',
    'Customer name' => 'Tên khách hàng',
    'Search'     => 'Tìm kiếm',
    'Reset' => 'Khôi phục',
    ' New' => ' Thêm mới',
    ' Export excel' => ' Xuất file excel',
    'Add new customer' => 'Tạo mới khách hàng',
    'Enter birth date' => 'Nhập ngày sinh',
    'Male'  => 'Nam',
    'Female' => 'Nữ',
    'Leave empty lines in generated code' => 'Bỏ trống để hệ thống tự sinh mã',
    'Save' => 'Lưu',
    'Success create customer with ID: ' => "Bạn đã tạo thành công khách hàng có ID: ",
    'Tax No' => 'Mã số thuế',
    'Bank Account' => 'Tài khoản NH',
    'Customer: #' =>'Khách hàng: #',
    ' was successfully deleted ' => ' đã được xóa thành công ',
    ' Click here</a> to proceed.' => "  Nhấn vào đây </a> để tiếp tục",
    'Saved record successfully' => 'Lưu thành công khách hàng',
    'Transctions count' => "Số lần giao dịch",
    'Revenues' => "Doanh thu",
    'Invoices history' => "Lịch sử các đơn hàng",
    'Disable' => "Ngừng GD",
    'Disable ?' => 'Ngừng giao dịch ?',
    'Phone numer seperated by commas' =>'Nhập nhiều số điện thoại ngăn cách bằng dấu phẩy ","',
    'Bank account seperated by commas' =>'Nhập nhiều tài khoản ngân hàng ngăn cách bằng dấu phẩy ","',
];
